### ISSUE TITLE
Full of expectation!

### ISSUE THREAD

**Issue by MidaAiZ** [soccerloway/quill-better-table#1]

**Comment by MidaAiZ** [comment]
哇 你竟然是个 Chinese，加油加油，期待你创造出优秀的 quill 表格

**Comment by soccerloway** [comment]
@MidaAiZ Thanks~我会加油滴~一会儿找到地方把demo放出来。

**Comment by soccerloway** [comment]
@MidaAiZ [quill-better-table demo](https://codepen.io/soccerloway/pen/WWJowj)
