### ISSUE TITLE
Is this intended for handling regular table html?

### ISSUE THREAD

**Issue by Jack-Collins** [soccerloway/quill-better-table#12]
If I initialize the editor with html which uses regular table tags, should this plugin parse it correctly?
I haven't been able to achieve this, but perhaps I am setting it up wrong.

**Comment by soccerloway** [comment]
Oh, it's really a depressing problem, thanks for reporting.
I will fix it soon.

**Comment by soccerloway** [comment]
@Jack-Collins hi,
I tried this in my codepen demo just now. 
It looks like the issue was fixed. Thanks again for your reporting.
I will close this issue.
If there is any problem, please tell me~thanks a lot.
