### ISSUE TITLE
Table in table rendering error

### ISSUE THREAD

**Issue by ZaynJarvis** [soccerloway/quill-better-table#13]
When the HTML to be rendered is a table in the table, it causes error.
![image](https://user-images.githubusercontent.com/31875147/63663270-50058f00-c7f4-11e9-9d7b-fa244ec701a2.png)
```html
<table border=1>
  <tbody>
    <tr>
      <td>1</td>
      <td>2</td>
      <td><table>
      <tbody>
        <tr>
          <td>3</td>
        </tr>
        <tr>
          <td>3</td>
        </tr>
        <tr>
          <td>3</td>
        </tr>
      </tbody>
    </table></td>
   </tr>
  <tr>
      <td>1</td>
      <td>2</td>
      <td>3</td>
    </tr>
  </tbody>
</table>
```

**Comment by soccerloway** [comment]
Can not support nested table structure now. It's really a complex feature and not a universal scene.

**Comment by soccerloway** [comment]
In my product, I disabled insert table when the cursor inside a table.

**Comment by soccerloway** [comment]
@ZaynJarvis I will close this issue~
By the way, your avator is so handsome~haha.
