### ISSUE TITLE
Plugin cannot work with Error

### ISSUE THREAD

**Issue by hanerx** [soccerloway/quill-better-table#15]
There are two errors when the editor loaded:
![image](https://user-images.githubusercontent.com/31791623/65209486-e31ba700-daca-11e9-8aa4-b7011335c15b.png)
And I cannot get module when I use getModule() function, it returns an undefined 
![image](https://user-images.githubusercontent.com/31791623/65209548-152d0900-dacb-11e9-882f-435b9b5aeb1e.png)

**Comment by soccerloway** [comment]
@hanerx If you use `quill-better-table` with `Vue-quill-editor` ? 
`quill-better-table` relies on **quilljs v2.0.0-dev.x**, not a released version, but `vue-quill-editor`  relies on quilljs 1.3.6.
So you can not use `quill-better-table` with `vue-quill-editor`.
Sorry about this.
