### ISSUE TITLE
td background can not initial corrent

### ISSUE THREAD

**Issue by kagol** [soccerloway/quill-better-table#17]
Copy a table which td has "background-color", and then paste it in editor, the table cell's background-color is wrong.
![image](https://user-images.githubusercontent.com/9566362/65573973-bb32b480-df9e-11e9-86a2-b43e4bdceaf8.png)
I noticed quill-better-table's new api "colors", support set background-color to table cell, but can't support initial/paste situation.
When can you support it？

**Comment by soccerloway** [comment]
@kagol Thanks for your report. I have fixed it this in v1.2.2.
I tried copying tables from macOS pages, and from plain HTML, then pasting into my editor.
It works well now.

**Comment by kagol** [comment]
@soccerloway Thanks for your fixing, that help me a lot.

**Comment by soccerloway** [comment]
@kagol You're welcome.

**Comment by lokesh8795** [comment]
Hi @soccerloway 
 i am using but the background color is working while pasting it from excel 
  "quill": "2.0.0-dev.3",
    "quill-better-table": "^1.2.10",
