### ISSUE TITLE
[bug]There will be a empty tr left if i delete the last row of a table

### ISSUE THREAD

**Issue by kagol** [soccerloway/quill-better-table#21]
This will cause the bottom border of the table to disappear.
![image](https://user-images.githubusercontent.com/9566362/66884646-72ea3d80-f004-11e9-92b0-4f148cbcab44.png)

**Comment by kagol** [comment]
The extra empty tr is unreasonable
![image](https://user-images.githubusercontent.com/9566362/66884809-ee4bef00-f004-11e9-8065-2cf01c45c948.png)

**Comment by soccerloway** [comment]
@kagol Fix in v1.2.3. Thanks for your report:)

**Comment by soccerloway** [comment]
@kagol Sorry, I forgot to bundle the module before publish.
Please update to `quill-better-table` v1.2.4.

**Comment by kagol** [comment]
Thank you for responding quickly and fixing this problem.
