### ISSUE TITLE
Multi whitespaces will become one when pasting

### ISSUE THREAD

**Issue by kagol** [soccerloway/quill-better-table#23]
I guess the quill version(2.0.0-dev.3) is a problem because there is no such problem on the Quill official website which use v1.3.6.

expect:
![image](https://user-images.githubusercontent.com/9566362/67448196-e0bbe800-f648-11e9-93f7-e45396296aaa.png)

actual:
![image](https://user-images.githubusercontent.com/9566362/67448173-ce41ae80-f648-11e9-9b27-7f887b3c31f8.png)

**Comment by soccerloway** [comment]
I tried in [quill 2.0.x official demo ](https://codepen.io/quill/pen/QxypzX). 
![image](https://user-images.githubusercontent.com/8068440/67449748-bf112f80-f64d-11e9-80fa-65719b117e63.png)
It's really a bug in quill 2.0.x-dev, it was mentioned in:
[quilljs issue 1751](https://github.com/quilljs/quill/issues/1751#issuecomment-338581862)
[quilljs issue 1752](https://github.com/quilljs/quill/issues/1752)
Hope these could help you.

**Comment by kagol** [comment]
I have seen these two issues, but i don't think this can solve this problem.
I think the reason is that the matchText judgment logic are inconsistent in quill v1.3.6 and v2.0.x-dev.
quill 1.3.6
![image](https://user-images.githubusercontent.com/9566362/67470316-1f20c980-f680-11e9-92af-c69356776db5.png)

quill 2.0.x-dev
![image](https://user-images.githubusercontent.com/9566362/67470279-10d2ad80-f680-11e9-9cfb-bc394fe589ba.png)

But i have no idea how to fix it.
