### ISSUE TITLE
在vue-quill-editor中无法正常显示table

### ISSUE THREAD

**Issue by zhuqingguang** [soccerloway/quill-better-table#27]
你好，我打算在vue-quill-editor中使用表格，所以自己fork了一份vue-quill-editor，然后升级了quill。
但是当我引入了better-table时，没有报错，但是表格却无法正常显示，请问有解决办法吗？
引入的代码如下：
```js
import { quillEditor, Quill } from '@ks/ks-vue-quill-editor';

Quill.register({
  'modules/better-table': QuillBetterTable
}, true)
```

**Comment by soccerloway** [comment]
@zhuqingguang hi,
我刚刚试了下，fork了一份vue-quill-editor，升级了quill之后，把重新打包后的dist/vue-quill-editor.js引入了我的页面，是可以正常使用的。
![image](https://user-images.githubusercontent.com/8068440/69022405-2ffdfa00-09f6-11ea-842d-794d060b3297.png)

![image](https://user-images.githubusercontent.com/8068440/69022523-8703cf00-09f6-11ea-8885-15214916058b.png)

![image](https://user-images.githubusercontent.com/8068440/69022632-d813c300-09f6-11ea-9a82-78b1f7c88715.png)

效果如下:
![image](https://user-images.githubusercontent.com/8068440/69022461-4f952280-09f6-11ea-964e-d87c2be5adee.png)

我猜你安装的vue-quill-editor可能依赖的还是quill v1.3.6. 你可以到node_modules中去看看vue-quill-editor的具体信息，看看dependences里quill版本是否正确。

**Comment by zhuqingguang** [comment]
非常感谢，同时非常抱歉，我之前没有注意到文档里面写的需要将Quill挂载到window上面。刚刚你的示例提醒了我。我是通过 `import` 来使用的：
```js
import 'quill/dist/quill.core.css';
import 'quill/dist/quill.snow.css';
import { quillEditor, Quill } from '@ks/ks-vue-quill-editor';
import ImageResize from '@ks/ks-quill-image-resize-module';
import QuillBetterTable from 'quill-better-table';
```
应该是跟使用方式有关系

**Comment by soccerloway** [comment]
友情提示：2.0毕竟还不是发布版本。相比1.3.6可能会遇到一些交互上的bug噢。我在我的产品里，quilljs也是fork了一份，方便修复一些bug……入坑需谨慎~^ _ ^!

**Comment by zhuqingguang** [comment]
满足基本需求就可以了，因为已经使用了quill一段时间了，再换编辑器，会影响以前创建的文档，但是有需要表格的支持

**Comment by AricZhu** [comment]
能详细说一下再 vue-quill-editor 中如何引入这个 quill-better-table 吗？ 我引入的时候还是报错了

**Comment by victorbuild** [comment]
請問有較詳細的解決步驟嗎？我將vue-quill-editor fork 並將版本修改為 2.0.0-dev.4

`"quill": "2.0.0-dev.4"  `

但插入表格時
只會出現

```
<p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>
```

**Comment by PixsaOJ** [comment]
What a great English issue, love it! Can somebody translate?

**Comment by alex644715** [comment]
> 請問有較詳細的解決步驟嗎？我將vue-quill-editor fork 並將版本修改為 2.0.0-dev.4
> 
> `"quill": "2.0.0-dev.4" `
> 
> 但插入表格時 只會出現
> 
> ```
> <p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p>
> ```
> 
> 我有搭配 vuex 不知道是不是 vuex的問題

我也遇到了这个问题，请问你解决了吗？
