### ISSUE TITLE
quill Cannot import modules/table. Are you sure it was registered?

### ISSUE THREAD

**Issue by zhengyn0001** [soccerloway/quill-better-table#28]
![image](https://user-images.githubusercontent.com/51322469/69592042-abcbf800-102f-11ea-86b1-48cbf0b115fc.png)
我试过在vue.config.js里面设置
config.plugin('provide').use(webpack.ProvidePlugin, [{
       'window.Quill': 'quill/dist/quill.js',
       'Quill': 'quill/dist/quill.js'
     }]),可是还是不成功，我想问一下你有遇到过这个问题吗，我是在vue里面使用的，我直接npm quill@2.0.0-dev.3

**Comment by soccerloway** [comment]
@zhengyn0001 你是不是在quil实例化的配置里面，加上了这些模块，但是却没有调用register注册它们呢？

**Comment by zhengyn0001** [comment]
我是这么用的
![image](https://user-images.githubusercontent.com/51322469/69592963-9dcba680-1032-11ea-8c9c-391ee401699f.png)

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/69593704-f734d500-1034-11ea-84f2-4645a60966e4.png)
我这样子貌似没遇到问题。

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/69594262-bfc72800-1036-11ea-9946-19e28c549376.png)
这样子可以正常使用，刚刚用vue-cli建了个项目试了下。
![image](https://user-images.githubusercontent.com/8068440/69594292-d4a3bb80-1036-11ea-8166-01456876e3e6.png)

**Comment by soccerloway** [comment]
你是在**vue-quill-editor**中使用吗？在vue-quill-editor中使用的话，还需要将vue-quill-editor依赖的quilljs版本升级至2.0.x.  #27 可以看看这个issue的问题。

**Comment by zhengyn0001** [comment]
我的版本是quill@2.0.0-dev.3，我已经确认过了

**Comment by soccerloway** [comment]
@zhengyn0001 加q？54760187

**Comment by soccerloway** [comment]
I made a fork for vue-quill-editor with quill 2.0, If someone wants to use `quill-better-table` with vue-quill-editor, use the configure below to instead official vue-quill-editor in `package.json`:
`"vue-quill2-editor": "https://git.coding.net/loway/vue-quill2-editor.git#b3ec62c694e4a54073eec038680b2627c55bd632"`
and then `yarn install`
![image](https://user-images.githubusercontent.com/8068440/69606887-ff096f00-105e-11ea-9741-a03c3fb6b86c.png)

**Comment by Alec-Aldrine-Lakra** [comment]
Check the quill version it should be 2.0.0-dev.3 , better table module does not work in quill 1.3.*

**Comment by v1talii-dev** [comment]
not work in quill 2.0.0-dev.3
