### ISSUE TITLE
add formatted text causes the table to split

### ISSUE THREAD

**Issue by bannerl** [soccerloway/quill-better-table#29]
example copy text with line feed，this will change a table into two.
Formatted text：
Updating a19799ec..dc10ea6d
Fast-forward

Copy and paste results:
![image](https://user-images.githubusercontent.com/24731436/69781352-d1503180-11e8-11ea-809d-85c4ddad4ada.png)

**Comment by soccerloway** [comment]
Is there something treat as block formats in the content you copied?
Like lists, headers and so on. Quill-better-table module can not support these in table cells.
![image](https://user-images.githubusercontent.com/8068440/69781947-9fd86580-11ea-11ea-88ca-14c7f56ba8f3.png)
But inline formats, it works well.

**Comment by soccerloway** [comment]
I haven't found a good way to support block in table cell yet. 
It was also mentioned in #7 and #20 , really a problem. 
Thanks for your report, and I will temporarily close this issue, we could discuss this in #20 .

**Comment by bannerl** [comment]
ok，thank you
