### ISSUE TITLE
复制粘贴网页内容时，有些内容会变成 table，格式错乱

### ISSUE THREAD

**Issue by blackChef** [soccerloway/quill-better-table#35]
似乎非连续文字的都会变成 table。
![1](https://user-images.githubusercontent.com/5157935/70604184-26516600-1c33-11ea-9eb2-a6fcf8884253.png)
![2](https://user-images.githubusercontent.com/5157935/70604189-2a7d8380-1c33-11ea-9011-8c49b23e611f.png)

**Comment by soccerloway** [comment]
从外部复制过来的内容来自剪切板，对于编辑器来说，这些内容不可控。也许内容中这段html就带有table>tr>td的结构。或者由于quill-better-table中的表格行是div，所以外部复制进来的div被解释成了table-cell-line块。

**Comment by soccerloway** [comment]
不建议直接从网页内容复制进入编辑器来录内容，因为很多网页在开发的时候，html标签常被乱用，如：table布局、将段落文字放在div下这一类，这是不符合html标签的语义的，粘贴进来容易出现各种异常。
