### ISSUE TITLE
[Bug]The col number is wrong when merge all columns and rows to a cell

### ISSUE THREAD

**Issue by kagol** [soccerloway/quill-better-table#37]
Insert a 3X3 table and merge all columns and row to a cell, the column number of top column control bar is wrong(expect 1 but 3):
![col-number-wrong-merge](https://user-images.githubusercontent.com/9566362/70903397-c5160200-2039-11ea-9788-b05a968e3573.png)

**Comment by soccerloway** [comment]
The top column control will not merge into one when the cells were merged. I think it is not a necessary feature. The number of top column controls means the max of columns or the number of <cols>.
