### ISSUE TITLE
Error: "Cannot import modules/formula. Are you sure it was registered?"

### ISSUE THREAD

**Issue by ninbit** [soccerloway/quill-better-table#38]
When I try to use the  `formula` module in your codepen example, it gives the error "Cannot import modules/formula. Are you sure it was registered?". (see it in [here](https://codepen.io/mirliva/pen/dyPZrYr)). Is this a limitation of `quill-2.0.0.-dev.0`? Or is it related to your implentation? How can I solve this issue? I want to use both formula and your better-table together.

Thanks for your hard work.

**Comment by soccerloway** [comment]
Hi @ninbit ,
`formula` is no longer a module in `quill-2.0.x`, but a format of `quill`. `formula` is registered as default. You just need to configure it in the toolbar, like:
![image](https://user-images.githubusercontent.com/8068440/71768982-5cde8000-2f56-11ea-822d-afbe6cc6ec5f.png)

**Comment by ninbit** [comment]
Thank you for your quick answer and your beautiful library!
