### ISSUE TITLE
请求兼容 1.3.x版本，请求帮助

### ISSUE THREAD

**Issue by carvinlo** [soccerloway/quill-better-table#39]
你好，目前有些扩展功能基于1.3.6基础开发，业务强要求兼容ie11，无法升级quill2
感谢老板，quill-better-table是个非常好的table插件，能否兼容quill 1.3.x版本呢，能实现基础创建表格跟粘贴表格就感激涕零了，自己看了源码，在渲染blot时报错：unable to create table blot，实在无法进行下去了，请求帮助，谢谢

**Comment by soccerloway** [comment]
对不起，回复得比较晚，谢谢你的支持~
我刚开始调研quilljs的时候，看到过一个基于quill 1.3.x的表格模块，不过功能比较简单，bug好像挺多，不妨看看它的实现能不能对你有所启发，[quill-table](https://github.com/dost/quilljs-table)。我选择基于quill 2.0.x-dev 实现这个表格模块，也是因为作者还活跃的时候，发过文章称，将在quill 2.0版本提供对table的支持，然后借鉴了作者那个最简易的表格模块实现了quill-better-table。quill2 和 quill1 依赖的parchment版本也是不同的，这套代码应该无法在1.x去运行。需要使用1.3.x的parchment系统去实现。
这段时间工作比较饱和，等有空的时候，可能能够去看看1.3.x有没有办法，可能不能很快帮到你。
希望我的回答对你有所帮助~
