### ISSUE TITLE
Table breaks if nested tables or new lines are inserted in table cells.

### ISSUE THREAD

**Issue by pvahia** [soccerloway/quill-better-table#40]
Content with nested tables/cells or new lines in cells breaks the table structure. 
Same happens when when pasting.

Is there a way to fix this?

**Comment by soccerloway** [comment]
Nested structure is always a pain in Quill. Only the classes extending from inline or embed are supported to insert in table cell lines, but headers, lists, tables… are not supported.

**Comment by soccerloway** [comment]
This problem was discussed in #20 #7 .

**Comment by djcurfew** [comment]
We really need a patch to allow lists (and multi-line) inside of table cells. In additional, ability to resize columns. We are offering bounty of $2,500 for this.
