### ISSUE TITLE
inserting <p> tag instead of table

### ISSUE THREAD

**Issue by sunilpune** [soccerloway/quill-better-table#44]
APP.COMPONENT.TS
-------------------------
`import {Component, OnInit, AfterViewInit, ViewChild, ElementRef} from '@angular/core';

import QuillBetterTable from 'quill-better-table';

declare const Quill: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent implements OnInit, AfterViewInit {
  @ViewChild('editable', {static: true}) editRef: ElementRef;

  quill: any;

  ngOnInit() {
    setTimeout(() => {
      this.initEditor();
    }, 1000);
  }

  initEditor(): void {
    Quill.register({
      'modules/better-table': QuillBetterTable
    }, true);
    // tslint:disable-next-line:no-unused-expression
    this.quill = new Quill(this.editRef.nativeElement, {
          theme: 'snow',
          modules: {
            table: false,
            'better-table': {
              operationMenu: {
                items: {
                  unmergeCells: {
                    text: 'Another unmerge cells name'
                  }
                }
              }
            },
            keyboard: {
              bindings: QuillBetterTable.keyboardBindings
            }
          }
        }
    );
  }
  ngAfterViewInit() {  }

  onInsertTable() {
    const tableModule = this.quill.getModule('better-table');
    tableModule.insertTable(3, 3);
  }
}
`

![Untitled](https://user-images.githubusercontent.com/3072340/75770882-dcc67200-5d6e-11ea-9c35-134625a8b44c.png)

its showing me above error if quill not installed and after installing quill with npm, code is working fine but only inserting `<p>` tag (paragraph tag) multiple times.

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/75973134-a2480b00-5f0f-11ea-9fef-35dd3c38dab0.png)

**Comment by akshaya-a-p** [comment]
I'm working in React JS apps, <p> tags are adding instead of table. I tired exposing quill js file in index.html file. but still facing same issue. Can I get help in resolving this issue
