### ISSUE TITLE
Update on support of multi-line and copy past on V2 version

### ISSUE THREAD

**Issue by aescaffre** [soccerloway/quill-better-table#51]
Hi,
Multi-line support on tables is a blocker on our project, where we integrated quill.js v2. Could you share if there are technical solutions that you can think of but you didn't implement them because you don't need it, or if it is just not possible from your perspective? 

Thank you !

**Comment by soccerloway** [comment]
Quill-better-table have already support Multi-line text in table cells, you can simply integrate and use.
About copying multi-line text and pasting into table cells, I have already solve it in my own project, it need to modify the quilljs original code. It was mentioned in the issue #33 .
Hope this helps:)
