### ISSUE TITLE
When merging n column cells it takes the width of 1 cell

### ISSUE THREAD

**Issue by Alec-Aldrine-Lakra** [soccerloway/quill-better-table#52]
How do I expand the width of the table cell in quill better table  ?

**Comment by soccerloway** [comment]
![image](https://user-images.githubusercontent.com/8068440/81147691-6a138600-8fad-11ea-9505-f1821d93363f.png)
Do you mean that after merging multiple columns, the cell width is incorrect?
After merging multiple columns, the cell width should be the sum of their widths, which seems to be correct.
