### ISSUE TITLE
incompatibility with quill 2.0.0.4

### ISSUE THREAD

**Issue by tedchou12** [soccerloway/quill-better-table#57]
I found quill 2.0.0.4
https://libraries.io/npm/quill

I am using 2.0.0.4 because 2.0.0.3 has some input issues especially with the Chinese input I am using.
(I think is a bug of 2.0.0.3

However I found out that quill-better-table has some errors with 2.0.0.4:
Javascript errors:
```
quill-better-table.min.js:2152 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at table_selection_TableSelection.mouseDownHandler (quill-better-table.min.js:2152)
mouseDownHandler @ quill-better-table.min.js:2152
```

<img width="1279" alt="截圖 2020-06-08 下午12 41 20" src="https://user-images.githubusercontent.com/10494709/83990679-63e64000-a985-11ea-8066-6a373499b24e.png">

Could I know if there could be possible fixes?
Thank you so much!

**Comment by tedchou12** [comment]
seems like is an issue with disabling the default button behavior.

**Comment by soccerloway** [comment]
@tedchou12 I was just watching:)

**Comment by soccerloway** [comment]
Did you have it worked well?

**Comment by tedchou12** [comment]
@soccerloway 
Thank you!
Actually, I found another error, when you combine (3,3) and (4,4), there will be empty space and those will cause errors:

```
quill-better-table.min.js:2162 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at HTMLDivElement.mouseMoveHandler (quill-better-table.min.js:2162)
mouseMoveHandler @ quill-better-table.min.js:2162
5quill-better-table.min.js:2942 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at HTMLDivElement.<anonymous> (quill-better-table.min.js:2942)
(anonymous) @ quill-better-table.min.js:2942
2quill-better-table.min.js:2152 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at table_selection_TableSelection.mouseDownHandler (
```

**Comment by tedchou12** [comment]
<img width="1268" alt="Screen Shot 2020-06-10 at 12 52 31" src="https://user-images.githubusercontent.com/10494709/84225099-4518b280-ab19-11ea-8b99-64fe8a54764e.png">

**Comment by frocelu** [comment]
I have the same error in quill version 2.0.0.3 and vue 2.6.11.
And in using other function like Add table column right.

It seems like can't get the selection cell/column/row correctly.
