### ISSUE TITLE
在vue项目中右键菜单无法显示如何解决

### ISSUE THREAD

**Issue by enjoyshuai** [soccerloway/quill-better-table#66]
![image](https://user-images.githubusercontent.com/29977687/95724187-9f34aa80-0ca8-11eb-84c7-314eddb6a87a.png)
以上是我的代码，希望大佬们能帮帮我

**Comment by weiQuill** [comment]
See if there is any errors in Dev-tool?

**Comment by enjoyshuai** [comment]
找到原因了，右键弹出的菜单层级太低被遮了。。。
